### ISSUE TITLE
Height feedback equals to 0

### ISSUE THREAD

**Issue by devgnrb** [monofox/python-linak-desk-control#1]
Hi, 
I'm using your code for a project and I think there is a bug. 
If I launch python program to get height, it return 0cm. If I move by 1cm the spring, it refresh the height after asking again the height. 

But I found why it's making this, so I suggest you to fix the code :) 
You just have to have `self.` before `_moveEnd():`,  at **line 284** so it look like that: 
`if not self._moveEnd():`

That fixed my problem 

Thanks !

**Comment by monofox** [comment]
Hi @devgnrb ,

thank you very much for this contribution. Indeed, the call is not correct and i pushed it.

For me its not executing the _moveEnd so i wonder why it might happen in your case.

Did it crashed for you with error `NameError: name '_moveEnd' is not defined` ?

If not, it might be, that we need to find another reason for your behavior.
If yes, we can close.

**Comment by devgnrb** [comment]
Yes, it crashed with the error is `name '_moveEnd' is not defined`

**Comment by monofox** [comment]
Thanks for your feedback and contribution. Than we can luckily close it.
